package Gerente;


import Administrador.Estoque;
import Utilitários.ConexaoCi;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Utilitários.DTO;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Oruam
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    public Funcionarios() {
        initComponents();
        DefaultTableModel modelot = (DefaultTableModel) JTFuncionarios.getModel();
        JTFuncionarios.setRowSorter(new TableRowSorter(modelot));
        String FilePath = "C:\\Users\\Josiel\\Desktop\\Daniel\\Programação\\Faetec\\Daniel - 221\\Ideal Fashion\\Java\\src\\DadosTabelas\\Funcionarios";
        File file = new File(FilePath) ;      
        try {
            FileReader frE = new FileReader (file);
            BufferedReader brE = new BufferedReader(frE);
            
            DefaultTableModel modelo = ( DefaultTableModel)JTFuncionarios.getModel();
            Object [ ] lines = brE.lines().toArray();
            
            for (int i = 0 ; i < lines.length; i ++){
                String [ ] row = lines[i].toString().split(" ");
                modelo.addRow(row);             
            }        
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Limpar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFuncionarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTCpf = new javax.swing.JFormattedTextField();
        JTData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JBRemoverTudo = new javax.swing.JButton();
        JBRemover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTNome = new javax.swing.JTextField();
        JTUsuario = new javax.swing.JTextField();
        JTSenha = new javax.swing.JTextField();
        JCSexo = new javax.swing.JComboBox<>();
        JBAtualizar = new javax.swing.JButton();
        JBAdicionar = new javax.swing.JButton();
        JCFuncao = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        Limpar.setText("jMenuItem1");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Limpar);

        setBorder(null);
        setClosable(true);
        setTitle("Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setName("Tela Funcionário"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFuncionarios.setBackground(new java.awt.Color(246, 242, 242));
        JTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Função", "Nome", "CPF", "Data de Nasc", "Sexo", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTFuncionarios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 520, 450));

        jPanel3.setBackground(new java.awt.Color(246, 242, 242));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("CPF:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("Data de Nascimento:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setText("Sexo:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        JTCpf.setBackground(new java.awt.Color(51, 51, 51));
        JTCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(JTCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, -1));

        JTData.setBackground(new java.awt.Color(51, 51, 51));
        JTData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTDataActionPerformed(evt);
            }
        });
        jPanel3.add(JTData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        jLabel6.setText("Função:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        JBRemoverTudo.setBackground(new java.awt.Color(255, 0, 0));
        JBRemoverTudo.setForeground(new java.awt.Color(255, 255, 255));
        JBRemoverTudo.setText("Remover tudo");
        JBRemoverTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverTudoActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemoverTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, 50));

        JBRemover.setBackground(new java.awt.Color(255, 0, 0));
        JBRemover.setForeground(new java.awt.Color(255, 255, 255));
        JBRemover.setText("Remover");
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 80, 50));

        jLabel8.setText("Usuário:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        JTNome.setBackground(new java.awt.Color(51, 51, 51));
        JTNome.setForeground(new java.awt.Color(255, 255, 255));
        JTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNomeActionPerformed(evt);
            }
        });
        jPanel3.add(JTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, -1));

        JTUsuario.setBackground(new java.awt.Color(51, 51, 51));
        JTUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, -1));

        JTSenha.setBackground(new java.awt.Color(51, 51, 51));
        JTSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, -1));

        JCSexo.setBackground(new java.awt.Color(246, 242, 242));
        JCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        JCSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCSexoActionPerformed(evt);
            }
        });
        jPanel3.add(JCSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        JBAtualizar.setBackground(new java.awt.Color(51, 102, 255));
        JBAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        JBAtualizar.setText("Atualizar");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 50));

        JBAdicionar.setBackground(new java.awt.Color(51, 102, 255));
        JBAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        JBAdicionar.setText("Adicionar");
        JBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 50));

        JCFuncao.setBackground(new java.awt.Color(246, 242, 242));
        JCFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Administrador", "Gerente" }));
        JCFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCFuncaoActionPerformed(evt);
            }
        });
        jPanel3.add(JCFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel10.setText("Senha:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, 460));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Dados do funcionário");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Funcionários");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarActionPerformed
        
        //Adiciona os dados ao banco de dados
        
        //Instância a classe DTO
        DTO dto = new DTO();
        
        //Intância a classe FuncionarioDTO de DTO
        DTO.FuncionarioDTO funcionarioDTO = dto.new FuncionarioDTO();
        
        //Seta os dados fornecidos para o FuncionarioDTO
        funcionarioDTO.setFuncao(JCFuncao.getSelectedItem().toString());
        funcionarioDTO.setNome(JTNome.getText());       
        funcionarioDTO.setCPF(JTCpf.getText());
        funcionarioDTO.setDataNascimento(JTData.getText());
        funcionarioDTO.setSexo(JCSexo.getSelectedItem().toString());
        funcionarioDTO.setUsuario(JTUsuario.getText());
        funcionarioDTO.setSenha(JTSenha.getText());
        
        //Instância a classe ConexaoCi
        ConexaoCi funcionarioDAO = new ConexaoCi();
        
        //Executa o insert dos dados setados na classe funcionarioDTO ao banco de dados através do funcionarioDAO
        int Resultado = funcionarioDAO.AdicionarFuncionario(funcionarioDTO);

        //Verifica se o cadastro foi efetuado com sucesso.
        if(Resultado != -1){
            //Grava os dados setados na classe funcionarioDTO para a tabela de cadastros através de um vetor
            DefaultTableModel Tabela = (DefaultTableModel) JTFuncionarios.getModel();
            Object[] dados = {funcionarioDTO.getFuncao(), funcionarioDTO.getNome(), funcionarioDTO.getCPF(), funcionarioDTO.getDataNascimento(), funcionarioDTO.getSexo(), funcionarioDTO.getCodigo()};
            Tabela.addRow(dados);

            //Salva a tabela
            String FilePath = "C:\\Users\\Josiel\\Desktop\\Daniel\\Programação\\Faetec\\Daniel - 221\\Ideal Fashion\\Java\\src\\DadosTabelas\\Funcionarios";
            File file = new File(FilePath);
            try {
                FileWriter fwe = new FileWriter(file);
                BufferedWriter bwe = new BufferedWriter(fwe);
                for (int i = 0; i < JTFuncionarios.getRowCount(); i ++){
                    for(int j = 0; j <  JTFuncionarios.getColumnCount(); j ++){
                        bwe.write(JTFuncionarios.getValueAt (i, j).toString() + " ");
                    }
                    bwe.newLine();
                }            
                bwe.close();
                fwe.close();
            }catch (IOException ex) {
                Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
            }
        }                                             
    }//GEN-LAST:event_JBAdicionarActionPerformed

    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed
        if(JTFuncionarios.getSelectedRow() != -1){                       
                JTFuncionarios.setValueAt(JTNome.getText(), JTFuncionarios.getSelectedRow(), 0);
                JTFuncionarios.setValueAt(JTUsuario.getText(), JTFuncionarios.getSelectedRow(),6);
                JTFuncionarios.setValueAt(JTSenha.getText(), JTFuncionarios.getSelectedRow(), 4);        
                JTFuncionarios.setValueAt(JTCpf.getText(), JTFuncionarios.getSelectedRow(), 2);
                JTFuncionarios.setValueAt(JTData.getText(), JTFuncionarios.getSelectedRow(), 3);
                JTFuncionarios.setValueAt(JCFuncao.getSelectedItem(), JTFuncionarios.getSelectedRow(), 1);
                JTFuncionarios.setValueAt(JCSexo.getSelectedItem(), JTFuncionarios.getSelectedRow(),5);           
        }else{
             JOptionPane.showMessageDialog(null, "Selecione uma linha para atualizar");
          }              
    }//GEN-LAST:event_JBAtualizarActionPerformed

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
       
          
    
        
        if(JTFuncionarios.getSelectedRow() != -1){
        
        DefaultTableModel modelop = (DefaultTableModel) JTFuncionarios.getModel();
        modelop.removeRow(JTFuncionarios.getSelectedRow());
       
        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }    
        
        
        
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        if(JTFuncionarios.getSelectedRow() != -1){

            DefaultTableModel modelo = (DefaultTableModel) JTFuncionarios.getModel();
            modelo.removeRow(JTFuncionarios.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_LimparActionPerformed

    private void JBRemoverTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverTudoActionPerformed

        int q = JOptionPane.showConfirmDialog(null,"Você tem Certeza?","Atenção", JOptionPane.YES_NO_OPTION);
        if(q == JOptionPane.YES_OPTION){
            DefaultTableModel modelo = (DefaultTableModel) JTFuncionarios.getModel();
            modelo.setNumRows(0);

        }

        else if(q == JOptionPane.NO_OPTION){

        }

    }//GEN-LAST:event_JBRemoverTudoActionPerformed

    private void JTDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTDataActionPerformed

    }//GEN-LAST:event_JTDataActionPerformed

    private void JTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNomeActionPerformed

    private void JTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFuncionariosMouseClicked
        // TODO add your handling code here:
        JTNome.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 0).toString());
        JTUsuario.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 1).toString());
        JTSenha.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 2).toString());
        JTCpf.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 3).toString());
        JTData.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 4).toString());
        JCFuncao.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 5).toString());
        JCSexo.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_JTFuncionariosMouseClicked

    private void JCSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCSexoActionPerformed

    private void JCFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCFuncaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionar;
    private javax.swing.JButton JBAtualizar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JButton JBRemoverTudo;
    private javax.swing.JComboBox<String> JCFuncao;
    private javax.swing.JComboBox<String> JCSexo;
    private javax.swing.JFormattedTextField JTCpf;
    private javax.swing.JFormattedTextField JTData;
    private javax.swing.JTable JTFuncionarios;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTextField JTSenha;
    private javax.swing.JTextField JTUsuario;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
