-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 15:23:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IdealFashion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IdealFashion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IdealFashion` ;
USE `IdealFashion` ;

-- -----------------------------------------------------
-- Table `IdealFashion`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IdealFashion`.`Clientes` (
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Residencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdealFashion`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IdealFashion`.`Estoque` (
  `Codigo` INT NOT NULL,
  `Tamanho` ENUM("M", "F") NOT NULL,
  `Quantidade` INT NOT NULL,
  `Preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdealFashion`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IdealFashion`.`Funcionarios` (
  `CPF` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Funcao` VARCHAR(45) NOT NULL,
  `DataNascimento` VARCHAR(10) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
