package Gerente;


import Administrador.Estoque;
import Utilitários.ConexaoCi;
import Utilitários.UsuarioDTO;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Utilitários.ConexaoBD;
import java.sql.Connection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Oruam
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFuncionarios
     */
    public Funcionarios() {
        initComponents();
        Connection conn = new ConexaoBD().ConectaBD();  
try {
    // Consulta para obter o total de linhas na tabela Estoque
    String sqlCount = "SELECT count(*) AS Total FROM Estoque";
    PreparedStatement pstmCount = conn.prepareStatement(sqlCount); 
    ResultSet resultCount = pstmCount.executeQuery();
    int total = 0;
    if (resultCount.next()) {
        total = resultCount.getInt("Total");
    }

    // Consulta para obter todos os registros da tabela Estoque
    String sqlSelect = "SELECT * FROM Estoque";
    PreparedStatement pstmSelect = conn.prepareStatement(sqlSelect);      
    ResultSet rs = pstmSelect.executeQuery();

    // Preenchimento da tabela JTFuncionarios
    int row = 0;
    while (rs.next() && row < total) { // Usando while loop para controlar a iteração
        JTFuncionarios.setValueAt(rs.getString("Funcao"), row, 0);
        JTFuncionarios.setValueAt(rs.getString("Nome"), row, 1);
        JTFuncionarios.setValueAt(rs.getString("CPF"), row, 2);
        JTFuncionarios.setValueAt(rs.getString("DataNascimento"), row, 3);
        JTFuncionarios.setValueAt(rs.getString("Sexo"), row, 4);
        JTFuncionarios.setValueAt(rs.getString("Usuario"), row, 5);
        JTFuncionarios.setValueAt(rs.getString("Senha"), row, 6);
        JTFuncionarios.setValueAt(rs.getString("Codigo"), row, 7);
        row++; // Incrementa o índice da linha
    }
} catch (SQLException erro) {
    JOptionPane.showMessageDialog(null, "Falha ao carregar a tabela." + erro.getMessage());
}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Limpar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTFuncionarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTCpf = new javax.swing.JFormattedTextField();
        JTData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        JBRemoverTudo = new javax.swing.JButton();
        JBRemover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTNome = new javax.swing.JTextField();
        JTUsuario = new javax.swing.JTextField();
        JTSenha = new javax.swing.JTextField();
        JCSexo = new javax.swing.JComboBox<>();
        JBAtualizar = new javax.swing.JButton();
        JBAdicionar = new javax.swing.JButton();
        JCFuncao = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        Limpar.setText("jMenuItem1");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Limpar);

        setBorder(null);
        setClosable(true);
        setTitle("Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setInheritsPopupMenu(true);
        setName("Tela Funcionário"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFuncionarios.setBackground(new java.awt.Color(246, 242, 242));
        JTFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Função", "Nome", "CPF", "Data de Nasc", "Sexo", "Usuário", "Senha", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTFuncionarios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 530, 520));

        jPanel3.setBackground(new java.awt.Color(246, 242, 242));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("CPF:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setText("Data de Nascimento:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel7.setText("Sexo:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        JTCpf.setBackground(new java.awt.Color(51, 51, 51));
        JTCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(JTCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, -1));

        JTData.setBackground(new java.awt.Color(51, 51, 51));
        JTData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            JTData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTDataActionPerformed(evt);
            }
        });
        jPanel3.add(JTData, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, -1));

        jLabel6.setText("Função:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        JBRemoverTudo.setBackground(new java.awt.Color(255, 51, 51));
        JBRemoverTudo.setForeground(new java.awt.Color(255, 255, 255));
        JBRemoverTudo.setText("Remover tudo");
        JBRemoverTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverTudoActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemoverTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 130, 50));

        JBRemover.setBackground(new java.awt.Color(255, 0, 0));
        JBRemover.setForeground(new java.awt.Color(255, 255, 255));
        JBRemover.setText("REMOVER");
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(JBRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 50));

        jLabel8.setText("Usuário:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        JTNome.setBackground(new java.awt.Color(51, 51, 51));
        JTNome.setForeground(new java.awt.Color(255, 255, 255));
        JTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNomeActionPerformed(evt);
            }
        });
        jPanel3.add(JTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 260, -1));

        JTUsuario.setBackground(new java.awt.Color(51, 51, 51));
        JTUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 200, -1));

        JTSenha.setBackground(new java.awt.Color(51, 51, 51));
        JTSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(JTSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, -1));

        JCSexo.setBackground(new java.awt.Color(246, 242, 242));
        JCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        JCSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCSexoActionPerformed(evt);
            }
        });
        jPanel3.add(JCSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        JBAtualizar.setBackground(new java.awt.Color(51, 102, 255));
        JBAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        JBAtualizar.setText("ATUALIZAR");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, 50));

        JBAdicionar.setBackground(new java.awt.Color(51, 102, 255));
        JBAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        JBAdicionar.setText("Adicionar");
        JBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 50));

        JCFuncao.setBackground(new java.awt.Color(246, 242, 242));
        JCFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendente", "Administrador", "Gerente" }));
        JCFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCFuncaoActionPerformed(evt);
            }
        });
        jPanel3.add(JCFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel10.setText("Senha:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarActionPerformed
        
        //Adiciona os dados ao banco de dados
        UsuarioDTO ObjusuarioDTO = new UsuarioDTO();

        ObjusuarioDTO.setNomeFuncionario(JTNome.getText());
        ObjusuarioDTO.setUsuarioFuncionario(JTUsuario.getText());
        ObjusuarioDTO.setSenhaFuncionario(JTSenha.getText());
        ObjusuarioDTO.setCPFFuncionario(JTCpf.getText());
        ObjusuarioDTO.setDataNascimentoFuncionario(JTData.getText());
        ObjusuarioDTO.setFuncaoFuncionario(JCFuncao.getSelectedItem().toString());
        ObjusuarioDTO.setSexoFuncionario(JCSexo.getSelectedItem().toString());

        ConexaoCi ObjusuarioDAO = new ConexaoCi();
        int Resultado = ObjusuarioDAO.AdicionarFuncionario(ObjusuarioDTO);

        if(Resultado != -1){
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");  
        }else{
            JOptionPane.showMessageDialog(null, "Usuário já cadastrado ou dados incorretos."); 
        }                                                
    }//GEN-LAST:event_JBAdicionarActionPerformed

    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed
        if(JTFuncionarios.getSelectedRow() != -1){                       
                JTFuncionarios.setValueAt(JTNome.getText(), JTFuncionarios.getSelectedRow(), 0);
                JTFuncionarios.setValueAt(JTUsuario.getText(), JTFuncionarios.getSelectedRow(),6);
                JTFuncionarios.setValueAt(JTSenha.getText(), JTFuncionarios.getSelectedRow(), 4);        
                JTFuncionarios.setValueAt(JTCpf.getText(), JTFuncionarios.getSelectedRow(), 2);
                JTFuncionarios.setValueAt(JTData.getText(), JTFuncionarios.getSelectedRow(), 3);
                JTFuncionarios.setValueAt(JCFuncao.getSelectedItem(), JTFuncionarios.getSelectedRow(), 1);
                JTFuncionarios.setValueAt(JCSexo.getSelectedItem(), JTFuncionarios.getSelectedRow(),5);           
        }else{
             JOptionPane.showMessageDialog(null, "Selecione uma linha para atualizar");
          }              
    }//GEN-LAST:event_JBAtualizarActionPerformed

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
       
          
    
        
        if(JTFuncionarios.getSelectedRow() != -1){
        
        DefaultTableModel modelop = (DefaultTableModel) JTFuncionarios.getModel();
        modelop.removeRow(JTFuncionarios.getSelectedRow());
       
        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }    
        
        
        
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        if(JTFuncionarios.getSelectedRow() != -1){

            DefaultTableModel modelo = (DefaultTableModel) JTFuncionarios.getModel();
            modelo.removeRow(JTFuncionarios.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_LimparActionPerformed

    private void JBRemoverTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverTudoActionPerformed

        int q = JOptionPane.showConfirmDialog(null,"Você tem Certeza?","Atenção", JOptionPane.YES_NO_OPTION);
        if(q == JOptionPane.YES_OPTION){
            DefaultTableModel modelo = (DefaultTableModel) JTFuncionarios.getModel();
            modelo.setNumRows(0);

        }

        else if(q == JOptionPane.NO_OPTION){

        }

    }//GEN-LAST:event_JBRemoverTudoActionPerformed

    private void JTDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTDataActionPerformed

    }//GEN-LAST:event_JTDataActionPerformed

    private void JTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNomeActionPerformed

    private void JTFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTFuncionariosMouseClicked
        // TODO add your handling code here:
        JTNome.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 0).toString());
        JTUsuario.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 1).toString());
        JTSenha.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 2).toString());
        JTCpf.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 3).toString());
        JTData.setText(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 4).toString());
        JCFuncao.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 5).toString());
        JCSexo.setSelectedItem(JTFuncionarios.getValueAt(JTFuncionarios.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_JTFuncionariosMouseClicked

    private void JCSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCSexoActionPerformed

    private void JCFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCFuncaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionar;
    private javax.swing.JButton JBAtualizar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JButton JBRemoverTudo;
    private javax.swing.JComboBox<String> JCFuncao;
    private javax.swing.JComboBox<String> JCSexo;
    private javax.swing.JFormattedTextField JTCpf;
    private javax.swing.JFormattedTextField JTData;
    private javax.swing.JTable JTFuncionarios;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTextField JTSenha;
    private javax.swing.JTextField JTUsuario;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
