-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 16:32:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema idealfashion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idealfashion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idealfashion` DEFAULT CHARACTER SET utf8mb4 ;
USE `idealfashion` ;

-- -----------------------------------------------------
-- Table `idealfashion`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`cliente` (
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `idealfashion`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`estoque` (
  `Nome` VARCHAR(45) NOT NULL,
  `Tamanho` VARCHAR(1) NOT NULL,
  `Quantidade` INT(11) NOT NULL,
  `Preco` DECIMAL(10,2) NOT NULL,
  `Codigo` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `idealfashion`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`funcionario` (
  `Funcao` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Codigo` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Codigo`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `Codigo_UNIQUE` (`Codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `idealfashion`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`venda` (
  `Data` VARCHAR(45) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  `NotaFiscal` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`NotaFiscal`),
  UNIQUE INDEX `NotaFiscal_UNIQUE` (`NotaFiscal` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `idealfashion`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`itens` (
  `Quantidade` INT NOT NULL,
  `Venda_notaFiscal` INT NOT NULL,
  `estoque_Codigo` INT(11) NOT NULL,
  PRIMARY KEY (`Venda_notaFiscal`, `estoque_Codigo`),
  INDEX `fk_pedidos_has_estoque_estoque1_idx` (`estoque_Codigo` ASC),
  INDEX `fk_pedidos_has_estoque_pedidos_idx` (`Venda_notaFiscal` ASC),
  CONSTRAINT `fk_pedidos_has_estoque_pedidos`
    FOREIGN KEY (`Venda_notaFiscal`)
    REFERENCES `idealfashion`.`venda` (`NotaFiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_estoque_estoque1`
    FOREIGN KEY (`estoque_Codigo`)
    REFERENCES `idealfashion`.`estoque` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
