-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 14:03:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idealfashion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idealfashion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idealfashion` ;
USE `idealfashion` ;

-- -----------------------------------------------------
-- Table `idealfashion`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`cliente` (
  `nome` INT NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `idcliente` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) ,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
COMMENT = 'nte';


-- -----------------------------------------------------
-- Table `idealfashion`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`estoque` (
  `produto` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `codigo` INT(11) NOT NULL,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) ,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idealfashion`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`funcionarios` (
  `funcao` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `codigo` INT(11) NOT NULL,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) ,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idealfashion`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `idealfashion`.`registro` (
  `Dataa` DATE NOT NULL,
  `Cliente` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `Produto` VARCHAR(45) NOT NULL,
  `Tamanho` VARCHAR(1) NOT NULL,
  `Quantidade` INT(11) NOT NULL,
  `NotaFiscal` INT(11) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  UNIQUE INDEX `NotaFiscal_UNIQUE` (`NotaFiscal` ASC) ,
  PRIMARY KEY (`NotaFiscal`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
